application: halperin-redir
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  expiration: "7d"
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /robots\.txt
  expiration: "7d"
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /admin.*
  script: admin.py
  login: admin

- url: .*
  script: main.py
